name: Nightly Build and Tests

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

env:
  FOUNDRY_PROFILE: ci

jobs:
  smart-contract-tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Foundry version
        run: forge --version

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv

      - name: Generate coverage report
        run: forge coverage --report lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./lcov.info
          flags: solidity
          name: smart-contract-coverage

  typescript-client-tests:
    name: TypeScript Client Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install TypeScript client dependencies
        run: cd ts-client && npm ci

      - name: Run unit tests with coverage
        run: cd ts-client && npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./ts-client/coverage/lcov.info
          flags: typescript
          name: typescript-client-coverage

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [smart-contract-tests, typescript-client-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install TypeScript client dependencies
        run: cd ts-client && npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run end-to-end integration tests
        run: |
          chmod +x ./scripts/manual-e2e-test.sh
          ./scripts/manual-e2e-test.sh

      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            anvil.log
            contract-address.txt

  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [smart-contract-tests, typescript-client-tests, integration-tests]
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "# Nightly Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Status" >> $GITHUB_STEP_SUMMARY
          echo "- Smart Contract Tests: ${{ needs.smart-contract-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- TypeScript Client Tests: ${{ needs.typescript-client-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Integration Tests: ${{ needs.integration-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Coverage Reports" >> $GITHUB_STEP_SUMMARY
          echo "- Coverage reports are available on Codecov" >> $GITHUB_STEP_SUMMARY